/**
 * prompt-builder.ts
 *
 * Pure function — no side effects, no injected dependencies.
 * Converts carousel slide / banner content + enriched metadata into a
 * detailed, Imagen 4-optimised visual prompt.
 *
 * Enrichment layers (applied when present, highest to lowest priority):
 *   1. brandVisualStyle  — Gemini Vision analysis of uploaded brand images
 *   2. personaDemographics — who the ad is targeting → scene/model cues
 *   3. angleEmotionalTrigger — angle's emotion → lighting/mood direction
 *   4. productName — product subject reference
 *   5. slideType / platform — format-specific composition defaults
 */

// ─── Interfaces ───────────────────────────────────────────────────────────────

export interface SlideContent {
  type:      string;          // cover | problem | value | solution | proof | tips | cta
  hook?:     string;
  headline:  string;
  body:      string;
}

export interface ImageMetadata {
  angle:     string;
  format:    string;          // carousel | banner | video
  platform:  string;          // instagram | tiktok | facebook | youtube

  // Phase 6 fields (existing)
  templateId?:   string | null;
  primaryColor?: string | null;

  // #4 enrichment — injected by carousel/banner generateImages()
  productName?:           string;   // e.g. "NutriFlow Pro"
  personaDemographics?:   string;   // e.g. "28-40 female, health-conscious, urban professional"
  brandVisualStyle?:      string;   // cached Gemini Vision description of uploaded images
  angleEmotionalTrigger?: string;   // emotional keyword from angle label, e.g. "fear", "pride"
}

export interface BannerContent {
  size:             string;   // e.g. '1200x628'
  headline:         string;
  subtext:          string;
  cta:              string;
  visual_direction: string;   // already generated by Claude
  layout?:          string;
}

// ─── Slide-type → visual direction ───────────────────────────────────────────

const SLIDE_VISUAL: Record<string, string> = {
  cover:    'bold hero shot, attention-grabbing composition, strong focal point, aspirational mood',
  problem:  'relatable struggle scene, candid documentary style, empathetic lighting, real-life context',
  value:    'clean lifestyle scene, product or concept in natural use, bright open environment',
  solution: 'transformation moment, confident subject, clear before-and-after energy, optimistic tone',
  proof:    'authentic social proof scene, people celebrating results, candid success moment',
  tips:     'instructional flatlay or step detail, clean minimal background, organised and clear',
  cta:      'aspirational outcome, dream result achieved, elevated lifestyle, warm inviting light',
};

// ─── Platform → composition cues ─────────────────────────────────────────────

const PLATFORM_STYLE: Record<string, string> = {
  instagram: 'square 1:1 composition, high saturation, polished aesthetic, feed-worthy',
  tiktok:    'square 1:1 crop of vertical energy, youthful and dynamic, bold colours',
  facebook:  'square 1:1, approachable and trustworthy, warm tones, community feel',
  youtube:   'square 1:1, cinematic quality, premium feel, high contrast',
  google:    'square 1:1, clean white-space friendly, professional, conversion-focused',
};

// ─── Banner size → aspect hint ────────────────────────────────────────────────

const BANNER_SIZE_ASPECT: Record<string, string> = {
  '1200x628':  'wide landscape 16:9',
  '1080x1080': 'square 1:1',
  '1080x1920': 'tall vertical 9:16 story',
  '300x250':   'compact rectangle',
  '728x90':    'ultra-wide leaderboard strip',
};

// ─── Angle emotional trigger → lighting/mood cue ─────────────────────────────
// Parses the angle label string for emotional keywords and returns a
// Imagen-optimised mood description.

function angleToMoodCue(angleLabel: string, trigger?: string): string {
  const a = (angleLabel + ' ' + (trigger ?? '')).toLowerCase();

  if (a.match(/fear|scarcity|miss.*out|fomo|urgency|lose/))
    return 'dramatic high-contrast lighting, tense atmospheric composition, sense of urgency, dark moody undertones';

  if (a.match(/pride|aspir|luxury|premium|elite|success|achieve/))
    return 'elevated lifestyle setting, warm golden-hour light, confident subjects, premium surroundings, aspirational mood';

  if (a.match(/curiosity|discover|mystery|reveal|intrig/))
    return 'intriguing visual composition, partial reveal, visual mystery element, inviting depth-of-field effect';

  if (a.match(/joy|happ|celebrat|fun|energet|excit/))
    return 'bright warm natural light, authentic laughter, energetic movement blur, vibrant saturated colours';

  if (a.match(/trust|credib|safe|proof|result|evidence/))
    return 'clean credible environment, face-to-camera connection, approachable warmth, clear sharp focus, professional clarity';

  if (a.match(/social|community|friend|togeth|connect/))
    return 'genuine human connection, group dynamic, candid shared moment, warm natural light, real interactions';

  if (a.match(/minimal|clean|simple|calm|peace/))
    return 'minimalist clean background, generous negative space, soft diffused light, calm and considered composition';

  return 'authentic lifestyle setting, natural light, commercial photography standard, clear subject focus';
}

// ─── Persona → visual scene cue ──────────────────────────────────────────────
// Translates persona demographics into visual scene direction so the
// generated image feels authentic to the target audience.

function personaToSceneCue(demographics: string): string {
  const d = demographics.toLowerCase();
  const parts: string[] = [];

  // Age range
  if (d.match(/\b(18|19|20|21|22|23|24|25)\b/) || d.match(/gen.?z|teen|young adult/))
    parts.push('young adult subject (20-25), energetic casual setting');
  else if (d.match(/\b(25|26|27|28|29|30|31|32|33|34|35)\b/) || d.match(/millennial/))
    parts.push('young professional subject (27-35)');
  else if (d.match(/\b(35|36|37|38|39|40|41|42|43|44|45)\b/) || d.match(/mid.?life|parent|mom|dad/))
    parts.push('adult subject (35-45), established lifestyle setting');
  else if (d.match(/50|55|60|senior|mature|boomer/))
    parts.push('mature adult subject (50+), refined dignified setting');

  // Gender
  if (d.match(/\bfemale|\bwoman|\bwomen|\bshe\b|\bher\b/))
    parts.push('female subject');
  else if (d.match(/\bmale|\bman|\bmen|\bhe\b|\bhim\b/))
    parts.push('male subject');

  // Lifestyle context
  if (d.match(/urban|city|metro|professional|exec/))
    parts.push('modern urban environment, clean contemporary setting');
  if (d.match(/health|fitness|active|athlet|wellness/))
    parts.push('active lifestyle setting, bright energetic environment');
  if (d.match(/parent|family|mom|dad|home/))
    parts.push('warm home environment, family-friendly setting');
  if (d.match(/luxury|wealth|high.?net|premium/))
    parts.push('premium upscale environment, refined aesthetic');
  if (d.match(/entrepreneur|startup|founder|business/))
    parts.push('modern workspace or creative studio setting');

  return parts.length ? parts.join(', ') : '';
}

// ─── Strip filler words from copy for visual concept extraction ───────────────

function extractVisualKeywords(text: string, maxChars = 120): string {
  return text
    .replace(/\b(the|a|an|is|are|and|or|but|with|for|of|in|on|at|to|you|your|we|our|this|that)\b/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, maxChars);
}

// ─── Slide prompt builder ─────────────────────────────────────────────────────

export function buildImagePrompt(slide: SlideContent, meta: ImageMetadata): string {
  const visualDir   = SLIDE_VISUAL[slide.type] ?? SLIDE_VISUAL['value'];
  const platformDir = PLATFORM_STYLE[meta.platform] ?? PLATFORM_STYLE['instagram'];
  const copyContext = extractVisualKeywords([slide.headline, slide.body].join(' '));

  // Enrichment blocks — only added when context is available
  const moodCue    = angleToMoodCue(meta.angle, meta.angleEmotionalTrigger);
  const sceneCue   = meta.personaDemographics ? personaToSceneCue(meta.personaDemographics) : '';
  const brandStyle = meta.brandVisualStyle    ? `Brand visual style (match this): ${meta.brandVisualStyle}` : '';
  const productRef = meta.productName         ? `Product/brand: ${meta.productName}.` : '';

  return [
    `Professional marketing photography for a ${meta.platform} ${meta.format} ad.`,
    productRef,
    `Visual concept: ${copyContext}.`,
    `Direction: ${visualDir}.`,
    `Mood / atmosphere: ${moodCue}.`,
    sceneCue   ? `Scene: ${sceneCue}.` : '',
    `Composition: ${platformDir}.`,
    brandStyle ? `${brandStyle}.` : 'Style: photorealistic, commercial photography, sharp focus, studio-grade lighting.',
    'No text, no words, no letters, no overlays in the image.',
  ].filter(Boolean).join(' ');
}

// ─── Banner prompt builder ────────────────────────────────────────────────────

export function buildBannerImagePrompt(banner: BannerContent, meta: ImageMetadata): string {
  const aspectHint  = BANNER_SIZE_ASPECT[banner.size] ?? 'standard display ad';
  const copyContext = extractVisualKeywords([banner.headline, banner.subtext].join(' '));

  const moodCue    = angleToMoodCue(meta.angle, meta.angleEmotionalTrigger);
  const sceneCue   = meta.personaDemographics ? personaToSceneCue(meta.personaDemographics) : '';
  const brandStyle = meta.brandVisualStyle    ? `Brand visual style (match this): ${meta.brandVisualStyle}` : '';
  const productRef = meta.productName         ? `Product/brand: ${meta.productName}.` : '';

  return [
    `Professional marketing photography for a ${banner.size} (${aspectHint}) display banner ad.`,
    productRef,
    `Visual concept: ${copyContext}.`,
    `Direction: ${banner.visual_direction}.`,
    `Mood / atmosphere: ${moodCue}.`,
    sceneCue   ? `Scene: ${sceneCue}.` : '',
    brandStyle ? `${brandStyle}.` : 'Style: photorealistic, commercial photography, sharp focus, studio-grade lighting.',
    'No text, no words, no letters, no overlays in the image.',
  ].filter(Boolean).join(' ');
}
