/**
 * prompt-builder.ts
 *
 * Pure function — no side effects, no injected dependencies.
 * Converts carousel slide content + campaign metadata into a
 * detailed, Imagen 4-optimised visual prompt.
 */

export interface SlideContent {
  type:      string;          // cover | problem | value | solution | proof | tips | cta
  hook?:     string;
  headline:  string;
  body:      string;
}

export interface ImageMetadata {
  angle:    string;
  format:   string;           // carousel | banner | video
  platform: string;           // instagram | tiktok | facebook | youtube
}

// ─── Slide-type → visual direction ──────────────────────────────────────────

const SLIDE_VISUAL: Record<string, string> = {
  cover:    'bold hero shot, attention-grabbing composition, strong focal point, aspirational mood',
  problem:  'relatable struggle scene, candid documentary style, empathetic lighting, real-life context',
  value:    'clean lifestyle scene, product or concept in natural use, bright open environment',
  solution: 'transformation moment, confident subject, clear before-and-after energy, optimistic tone',
  proof:    'authentic social proof scene, people celebrating results, candid success moment',
  tips:     'instructional flatlay or step detail, clean minimal background, organised and clear',
  cta:      'aspirational outcome, dream result achieved, elevated lifestyle, warm inviting light',
};

// ─── Platform → composition cues ─────────────────────────────────────────────

const PLATFORM_STYLE: Record<string, string> = {
  instagram: 'square 1:1 composition, high saturation, polished aesthetic, feed-worthy',
  tiktok:    'square 1:1 crop of vertical energy, youthful and dynamic, bold colours',
  facebook:  'square 1:1, approachable and trustworthy, warm tones, community feel',
  youtube:   'square 1:1, cinematic quality, premium feel, high contrast',
  google:    'square 1:1, clean white-space friendly, professional, conversion-focused',
};

// ─── Core builder ─────────────────────────────────────────────────────────────

// ─── Banner prompt ────────────────────────────────────────────────────────────

export interface BannerContent {
  size:              string;   // e.g. '1200x628'
  headline:          string;
  subtext:           string;
  cta:               string;
  visual_direction:  string;   // already generated by Claude
  layout?:           string;
}

const BANNER_SIZE_ASPECT: Record<string, string> = {
  '1200x628':  'wide landscape 16:9',
  '1080x1080': 'square 1:1',
  '1080x1920': 'tall vertical 9:16 story',
  '300x250':   'compact rectangle',
  '728x90':    'ultra-wide leaderboard strip',
};

export function buildBannerImagePrompt(banner: BannerContent, meta: ImageMetadata): string {
  const aspectHint  = BANNER_SIZE_ASPECT[banner.size] ?? 'standard display ad';
  const copyContext = [banner.headline, banner.subtext]
    .join(' ')
    .replace(/\b(the|a|an|is|are|and|or|but|with|for|of|in|on|at|to)\b/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 120);

  return [
    `Professional marketing photography for a ${banner.size} (${aspectHint}) display banner ad.`,
    `Visual concept: ${copyContext}.`,
    `Direction: ${banner.visual_direction}.`,
    `Angle / tone: ${meta.angle}.`,
    'Style: photorealistic, commercial photography, sharp focus, studio-grade lighting.',
    'No text, no words, no letters, no overlays in the image.',
  ].join(' ');
}

// ─── Slide prompt ─────────────────────────────────────────────────────────────

export function buildImagePrompt(slide: SlideContent, meta: ImageMetadata): string {
  const visualDir  = SLIDE_VISUAL[slide.type]  ?? SLIDE_VISUAL['value'];
  const platformDir = PLATFORM_STYLE[meta.platform] ?? PLATFORM_STYLE['instagram'];

  // Distil copy to key visual nouns/verbs (strip filler words)
  const copyContext = [slide.headline, slide.body]
    .join(' ')
    .replace(/\b(the|a|an|is|are|and|or|but|with|for|of|in|on|at|to)\b/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 120);

  return [
    `Professional marketing photography for a ${meta.platform} ${meta.format} ad.`,
    `Visual concept: ${copyContext}.`,
    `Direction: ${visualDir}.`,
    `Angle / tone: ${meta.angle}.`,
    `Composition: ${platformDir}.`,
    'Style: photorealistic, commercial photography, sharp focus, studio-grade lighting.',
    'No text, no words, no letters, no overlays in the image.',
  ].join(' ');
}
