/**
 * job.types.ts
 *
 * Redis queue job definitions for the UGC Engine.
 *
 * Job lifecycle:
 *   queued → processing → done | failed
 */

import type { UGCVariant }         from '../types/ugc.types';
import type { KlingCompilerOutput } from '../types/ugc.types';
import type { HookVariantId }       from '../types/viral-test.types';

// ─── Job payload ──────────────────────────────────────────────────────────────

export interface UGCJobPayload {
  /** Unique job identifier */
  jobId:         string;
  campaignId:    string;
  /** Optional concept linkage */
  conceptId?:    string;
  platform:      string;
  /** Duration in seconds: 15 | 60 | 90 */
  durationSeconds: number;
  /** Compiled variant ready for rendering */
  variant:       UGCVariant;
  /** Kling compiler output — scene-by-scene render plan */
  compiledPlan:  KlingCompilerOutput;
  /** ISO timestamp */
  enqueuedAt:    string;

  // ── Phase 1.1 viral test fields (optional for backward compat) ───────────
  /** Test run identifier — groups all jobs in a viral test */
  testId?:       string;
  /** Expanded variant ID e.g. "skeptical_user-A" */
  variantId?:    string;
  /** Hook slot within the test: A | B | C */
  hookId?:       HookVariantId;
}

// ─── Job status record ────────────────────────────────────────────────────────

export type UGCJobState = 'queued' | 'processing' | 'done' | 'failed';

export interface UGCJobRecord {
  jobId:             string;
  campaignId:        string;
  conceptId?:        string;
  platform:          string;
  state:             UGCJobState;
  persona:           string;
  hook:              string;
  /** Stitched output video URL (set when state = 'done') */
  stitchedVideoUrl?: string;
  /** Individual scene video URLs */
  sceneVideoUrls?:   string[];
  /** UGC scoring (0–1) */
  score?:            number;
  error?:            string;
  enqueuedAt:        string;
  startedAt?:        string;
  completedAt?:      string;

  // ── Phase 1.1 viral test fields ──────────────────────────────────────────
  testId?:       string;
  variantId?:    string;
  hookId?:       string;

  // ── FIX 6: Full variant data persisted to avoid lossy reconstruction ──────
  /** Full UGC script as generated by VariantService */
  fullScript?:        string;
  /** Hook strategy + emotional arc (e.g. "relatable_pain → curiosity → relief") */
  emotionalStrategy?: string;
  /** Pre-render score estimate from ExpandedVariantService (0–1) */
  ugcScoreEstimate?:  number;
}

// ─── Queue keys ───────────────────────────────────────────────────────────────

export const UGC_QUEUE_KEY  = 'ugc:queue:pending';
export const UGC_JOB_PREFIX = 'ugc:job:';

export function ugcJobKey(jobId: string): string {
  return `${UGC_JOB_PREFIX}${jobId}`;
}
